
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LCHAVE = 34;
  public static final int INTEGER = 3;
  public static final int LPAREN = 32;
  public static final int RCHAVE = 35;
  public static final int LESS = 25;
  public static final int MINUS = 22;
  public static final int VIRGULA = 29;
  public static final int STATIC = 12;
  public static final int RPAREN = 33;
  public static final int AND = 24;
  public static final int CLASS = 9;
  public static final int PLUS = 21;
  public static final int ASSIGN = 26;
  public static final int MAIN = 14;
  public static final int IF = 5;
  public static final int RCOCHETE = 31;
  public static final int THIS = 17;
  public static final int DOT = 28;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int TRUE = 15;
  public static final int SCOLON = 36;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int NEGATION = 27;
  public static final int VOID = 13;
  public static final int ELSE = 6;
  public static final int WHILE = 7;
  public static final int PUBLIC = 11;
  public static final int EXTENDS = 10;
  public static final int MULTI = 23;
  public static final int BOOLEANO = 2;
  public static final int SYSO = 20;
  public static final int STRING = 4;
  public static final int FALSE = 16;
  public static final int LENGTH = 18;
  public static final int LCOCHETE = 30;
  public static final int INTEGER_LITERAL = 38;
  public static final int IDENTIFIER = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOLEANO",
  "INTEGER",
  "STRING",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "CLASS",
  "EXTENDS",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "TRUE",
  "FALSE",
  "THIS",
  "LENGTH",
  "NEW",
  "SYSO",
  "PLUS",
  "MINUS",
  "MULTI",
  "AND",
  "LESS",
  "ASSIGN",
  "NEGATION",
  "DOT",
  "VIRGULA",
  "LCOCHETE",
  "RCOCHETE",
  "LPAREN",
  "RPAREN",
  "LCHAVE",
  "RCHAVE",
  "SCOLON",
  "IDENTIFIER",
  "INTEGER_LITERAL"
  };
}

